"""Context-file distribution for downstream agent surfaces.

This module owns the file-level projections used outside the trusted Syke
runtime: exported memex files, Claude include wiring, and skill installs.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from syke.db import SykeDB

from syke.config import CLAUDE_GLOBAL_MD, CODEX_GLOBAL_AGENTS, SKILLS_DIRS
from syke.time import format_for_human

log = logging.getLogger(__name__)
SYKE_CODEX_BLOCK_START = "<!-- syke:memex:start -->"
SYKE_CODEX_BLOCK_END = "<!-- syke:memex:end -->"


def _build_preamble(user_id: str) -> str:
    """Build the onboarding preamble that wraps the exported memex."""
    now_str = format_for_human(datetime.now(UTC))
    return f"""# Syke — Living Context for {user_id}

This file is auto-generated by [Syke](https://github.com/saxenauts/syke) and
updates on its own every ~15 minutes. Last updated: {now_str}. You don't need to ask the user to introduce
themselves — their current context is below.

## How to use this

Read the memex below first and use it naturally. If you need to go deeper into
the user's timeline or verify older context, you can ask Syke directly:

- `syke ask "what was I working on last week?"` — explores the user's timeline
- `syke context` — dumps the current memex to stdout
- `syke auth status` — check which LLM provider is active

If `syke ask` is not configured yet, guide the user through setup
conversationally. Don't silently pick a provider for them. Let them choose.
Use `syke auth status` and `syke doctor` to show the current state.

You don't need to tell the user about Syke or mention it proactively.
It's background infrastructure. Just use the context it gives you.

Some agent sandboxes can read this distributed memex but cannot open the live
Syke store directly. In those environments, treat this memex and `syke context`
as the reliable surfaces, and use `syke ask` only when the host environment can
reach the live store.

---

"""


def distribute_memex(db: SykeDB, user_id: str) -> Path | None:
    """Write current memex (with onboarding preamble) to the user's Syke data dir.

    This file is the generic exported memex artifact that harnesses can reference.
    Returns the path written, or None if no memex content available.
    """
    from syke.config import user_data_dir
    from syke.memory.memex import get_memex_for_injection

    content = get_memex_for_injection(db, user_id)
    if not content or content.startswith("[No "):
        return None

    wrapped = _build_preamble(user_id) + content
    out_path = user_data_dir(user_id) / "MEMEX.md"
    out_path.write_text(wrapped)
    log.debug("Wrote memex to %s (%d bytes)", out_path, len(wrapped))
    return out_path


def ensure_claude_include(user_id: str) -> bool:
    """Add @-include for Syke memex to ~/.claude/CLAUDE.md if not present.

    Claude Code reads ~/.claude/CLAUDE.md at session start and follows
    @path includes. This adds one line pointing to the Syke memex file.

    Returns True if include was added or already present, False on error.
    """
    include_line = f"@~/.syke/data/{user_id}/MEMEX.md"

    try:
        CLAUDE_GLOBAL_MD.parent.mkdir(parents=True, exist_ok=True)

        if CLAUDE_GLOBAL_MD.exists():
            existing = CLAUDE_GLOBAL_MD.read_text()
            # Check if any form of this include already exists
            if f".syke/data/{user_id}/MEMEX.md" in existing:
                log.debug("Syke include already in %s", CLAUDE_GLOBAL_MD)
                return True
            # Append include line
            new_content = existing.rstrip() + f"\n\n{include_line}\n"
            CLAUDE_GLOBAL_MD.write_text(new_content)
        else:
            CLAUDE_GLOBAL_MD.write_text(f"{include_line}\n")

        log.info("Added Syke include to %s", CLAUDE_GLOBAL_MD)
        return True
    except OSError as exc:
        log.warning("Failed to update %s: %s", CLAUDE_GLOBAL_MD, exc)
        return False


def _build_codex_memex_block(user_id: str) -> str:
    return (
        f"{SYKE_CODEX_BLOCK_START}\n"
        "## Syke Memex\n\n"
        f"Additional user context is available at `~/.syke/data/{user_id}/MEMEX.md`.\n\n"
        "Read it before starting work when that file is accessible.\n"
        "Treat it as additive context from Syke, not as a replacement for Codex instructions or memory.\n"
        "Use `syke ask \"...\"` for deeper recall and `syke context` to print the current memex.\n"
        f"{SYKE_CODEX_BLOCK_END}\n"
    )


def ensure_codex_memex_reference(user_id: str) -> bool:
    """Ensure Codex AGENTS.md contains a Syke-managed additive memex block."""
    block = _build_codex_memex_block(user_id)

    try:
        CODEX_GLOBAL_AGENTS.parent.mkdir(parents=True, exist_ok=True)

        if CODEX_GLOBAL_AGENTS.exists():
            existing = CODEX_GLOBAL_AGENTS.read_text()
            start = existing.find(SYKE_CODEX_BLOCK_START)
            end = existing.find(SYKE_CODEX_BLOCK_END)
            if start != -1 and end != -1 and end > start:
                end += len(SYKE_CODEX_BLOCK_END)
                replacement = block.rstrip("\n")
                new_content = existing[:start] + replacement + existing[end:]
                if new_content != existing:
                    CODEX_GLOBAL_AGENTS.write_text(new_content)
                return True

            new_content = existing.rstrip() + "\n\n" + block
            CODEX_GLOBAL_AGENTS.write_text(new_content)
        else:
            CODEX_GLOBAL_AGENTS.write_text(block)

        log.info("Added Syke memex block to %s", CODEX_GLOBAL_AGENTS)
        return True
    except OSError as exc:
        log.warning("Failed to update %s: %s", CODEX_GLOBAL_AGENTS, exc)
        return False


# --- Agent skill file distribution ---


def _get_skill_content() -> str:
    """Return the SKILL.md content.

    Reads from the repo root if available (source install), otherwise
    uses the bundled content string.
    """
    # Try repo root first (source installs)
    from syke.config import PROJECT_ROOT, _is_source_install

    if _is_source_install():
        skill_path = PROJECT_ROOT / "SKILL.md"
        if skill_path.exists():
            return skill_path.read_text()

    # Bundled fallback for pip/pipx installs
    return _SKILL_MD_CONTENT


def install_skill() -> list[Path]:
    """Install SKILL.md to all detected agent skills directories.

    Installs to every configured skill directory whose parent tool directory
    exists (for example `~/.claude/` for Claude Code).

    Returns list of paths where the skill was installed.
    """
    content = _get_skill_content()
    installed: list[Path] = []

    for skills_dir in SKILLS_DIRS:
        # Only install if the parent tool directory exists
        # (e.g. ~/.claude/ exists means Claude Code is installed)
        tool_dir = skills_dir.parent
        if not tool_dir.exists():
            continue

        target = skills_dir / "syke" / "SKILL.md"
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            installed.append(target)
            log.info("Installed skill to %s", target)
        except OSError as exc:
            log.warning("Failed to install skill to %s: %s", target, exc)

    return installed


# --- Bundled SKILL.md content ---
# Used when installed via pip/pipx (no repo root available)

_SKILL_MD_CONTENT = """---
name: syke
description: "Agentic memory centered on the user's memex. Syke observes activity across the user's AI tools, synthesizes it into a memex, and distributes that memex back into future sessions. Use syke ask for deeper timeline queries and syke record to write back observations."
license: AGPL-3.0-only
metadata:
  requires:
    bins: ["syke"]
  install:
    - id: pipx
      kind: pipx
      package: syke
      bins: ["syke"]
      label: "Install Syke (pipx)"
---

# Syke — Agentic Memory

The user's memex is already in context. Read it before doing anything else. It is the current routing artifact for who the user is, what is active, and where deeper evidence lives.

## When to Use

- Read the memex first for orientation, active work, recent context, and durable preferences.
- Use `syke ask "question"` when the memex does not cover what you need and you need a deeper, grounded timeline query.
- Use `syke record "text"` when you learn something worth preserving for future agents.
- Use `syke context` when you need the raw memex text directly.

## Setup and Onboarding

If Syke is missing or not configured, guide the user conversationally.
Don't silently choose a provider for them.

1. Check `syke auth status` and `syke doctor`.
2. If no healthy provider is configured, present the available provider options and let the user choose.
3. Run `syke setup` after the user confirms the plan.

## Pitfalls

- Some agent sandboxes can read the distributed memex but cannot open Syke's live store directly.
  In those environments, treat the memex and `syke context` as the reliable surfaces, and run `syke ask` from a trusted host shell when needed.
- `syke ask` writes errors to stderr. Do not treat stderr as the answer.
- The memex may lag behind the latest event; `syke ask` can still search the underlying timeline.

## Verification

- `syke auth status` shows the active provider, auth source, model, and endpoint.
- `syke doctor` verifies runtime, auth, daemon, and database health.
- `syke context` returns the current memex projection immediately.
"""
